# Generated by Django 5.1 on 2024-12-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_asset_info',
            old_name='expected_life_post',
            new_name='expected_life',
        ),
        migrations.RemoveField(
            model_name='model_asset_info',
            name='expected_life_pre',
        ),
    ]
