# Generated by Django 5.1 on 2024-12-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfinder_sales',
            name='Asset_Code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sales_entry_model',
            name='Asset_code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sales_entry_model',
            name='Financial_year',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sales_entry_model',
            name='Number',
            field=models.IntegerField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sales_entry_model',
            name='Sales_proceeds',
            field=models.FloatField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sales_entry_model',
            name='Year_elapsed',
            field=models.IntegerField(max_length=256, null=True),
        ),
    ]
