# Generated by Django 5.1 on 2024-12-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesentry', '0002_alter_entryfinder_sales_asset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_entry_model',
            name='Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales_entry_model',
            name='Year_elapsed',
            field=models.IntegerField(null=True),
        ),
    ]
