# Generated by Django 5.1 on 2024-12-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impairmenttest', '0005_impairmententry_model_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfinderm',
            name='Asset_Code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='impairmententry_model',
            name='Asset_Code',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='impairmententry_model',
            name='Fair_value_less_cost_to_sale',
            field=models.FloatField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='impairmententry_model',
            name='Financial_year',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='impairmententry_model',
            name='Value_in_use',
            field=models.FloatField(max_length=256, null=True),
        ),
    ]
